name: dms_heatmap

channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=5.4.1
  - jupyterlab
  - nbstripout
  - numpy<2 
  - pandas
  - pip
  - pyarrow
  - python=3.12
  - ruff
  - vl-convert-python
  - pip:
      - httpimport

